Add desktop implementations
MisterJimson/flutter_keyboard_visibility pull request #123
Opened 2022-10-04 14:02 UTC by cbenhagen

For now all implementations return false.

Partially fixes #87

2022-10-04 14:52 UTC, MisterJimson commented
Dude this is awesome! Will take a look asap.

2022-10-04 15:02 UTC, MisterJimson commented
Trying to test macos desktop.

I've changed `flutter_keyboard_visibility/pubspec.yaml` to point to path deps so I can `pub get`.

`flutter run -d macos` results in:

```
➜  example git:(desktop) ✗ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             722ms
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-000459DE3441801E }
{ platform:macOS, arch:x86_64, id:00006001-000459DE3441801E }
.dart_tool/flutter_build/dart_plugin_registrant.dart:22:9: Error: 'FlutterKeyboardVisibilityPlugin' is imported from both 'package:flutter_keyboard_visibility_linux/flutter_keyboard_visibility_linux.dart' and 'package:flutter_keyboard_visibility_macos/flutter_keyboard_visibility_macos.dart'.
        FlutterKeyboardVisibilityPlugin.registerWith();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.dart_tool/flutter_build/dart_plugin_registrant.dart:33:9: Error: 'FlutterKeyboardVisibilityPlugin' is imported from both 'package:flutter_keyboard_visibility_linux/flutter_keyboard_visibility_linux.dart' and 'package:flutter_keyboard_visibility_macos/flutter_keyboard_visibility_macos.dart'.
        FlutterKeyboardVisibilityPlugin.registerWith();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.dart_tool/flutter_build/dart_plugin_registrant.dart:44:9: Error: 'FlutterKeyboardVisibilityPlugin' is imported from both 'package:flutter_keyboard_visibility_linux/flutter_keyboard_visibility_linux.dart' and 'package:flutter_keyboard_visibility_macos/flutter_keyboard_visibility_macos.dart'.
        FlutterKeyboardVisibilityPlugin.registerWith();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```

2022-10-04 15:05 UTC, MisterJimson commented
From this doc page: https://docs.flutter.dev/development/packages-and-plugins/developing-packages#dart-only-platform-implementations

It seems like each plugin should use a different class name. So `FlutterKeyboardVisibilityPlugin` -> `FlutterKeyboardVisibilityPluginMacos` for the macos package

2022-10-04 16:53 UTC, cbenhagen commented
Strange, I wonder why this worked on my machine. But renaming is for sure a good idea. I also updated the README.

2022-10-04 19:53 UTC, MisterJimson requested changes
Awesome work, really appreciate it. Some minor changes and questions.

2022-10-04 19:53 UTC, MisterJimson commented on flutter_keyboard_visibility_linux/README.md
> +Web support for Flutter Keyboard Visibility
```suggestion
Linux support for Flutter Keyboard Visibility
```

2022-10-04 19:53 UTC, MisterJimson commented on flutter_keyboard_visibility_linux/pubspec.yaml
> +    sdk: flutter
Is this needed?

2022-10-04 19:53 UTC, MisterJimson commented on flutter_keyboard_visibility_macos/README.md
> +Web support for Flutter Keyboard Visibility
```suggestion
macOS support for Flutter Keyboard Visibility
```

2022-10-04 19:53 UTC, MisterJimson commented on flutter_keyboard_visibility_windows/README.md
> +# Flutter Keyboard Visibility Web
```suggestion
# Flutter Keyboard Visibility Windows
```

2022-10-04 19:53 UTC, MisterJimson commented on flutter_keyboard_visibility_windows/README.md
> +Web support for Flutter Keyboard Visibility
```suggestion
Windows support for Flutter Keyboard Visibility
```

2022-10-04 19:53 UTC, MisterJimson commented on flutter_keyboard_visibility_windows/pubspec.yaml
> +    sdk: flutter
Is this needed?

2022-10-08 13:13 UTC, MisterJimson approved these changes

2022-10-08 13:14 UTC, merged

2022-10-08 13:24 UTC, cbenhagen commented
@MisterJimson sorry I had to pause my work on this for a moment. Thanks for finishing the PR!

2022-10-08 13:34 UTC, MisterJimson commented
No worries at all!